In [2]:
!pip install spacy

    100% |████████████████████████████████| 3.3MB 38kB/s ta 0:00:018
    100% |████████████████████████████████| 92kB 35kB/s ta 0:00:01
    100% |████████████████████████████████| 931kB 32kB/s ta 0:00:01
    100% |████████████████████████████████| 51kB 57kB/s ta 0:00:01
    100% |████████████████████████████████| 194kB 46kB/s ta 0:00:01
    100% |████████████████████████████████| 92kB 42kB/s ta 0:00:01
    100% |████████████████████████████████| 92kB 57kB/s ta 0:00:01
    100% |████████████████████████████████| 604kB 51kB/s ta 0:00:01
    100% |████████████████████████████████| 51kB 43kB/s ta 0:00:01
    100% |████████████████████████████████| 51kB 93kB/s ta 0:00:0111
    100% |████████████████████████████████| 389kB 61kB/s ta 0:00:01
    100% |████████████████████████████████| 133kB 39kB/s ta 0:00:01
    100% |████████████████████████████████| 143kB 51kB/s ta 0:00:01
  Using cached certifi-2017.4.17-py2.py3-none-any.whl
    100% |████████████████████████████████| 61kB 68kB/s ta 0:00:0

In [5]:
!python -m spacy download en



    100% |████████████████████████████████| 52.2MB 168kB/s ta 0:00:011
  Running setup.py install for en-core-web-sm ... done

    Linking successful

    /Users/heytitle/projects/neural-network-project/python3-env/lib/python3.5/site-packages/en_core_web_sm/en_core_web_sm-1.2.0
    -->
    /Users/heytitle/projects/neural-network-project/python3-env/lib/python3.5/site-packages/spacy/data/en

    You can now load the model via spacy.load('en').



In [6]:
!pip install gensim

    100% |████████████████████████████████| 6.4MB 111kB/s ta 0:00:011
    100% |████████████████████████████████| 1.4MB 197kB/s ta 0:00:01
  Running setup.py bdist_wheel for smart-open ... done
  Stored in directory: /Users/heytitle/Library/Caches/pip/wheels/b0/81/ad/856aade935fceaab491a800ec4de58edb8642afa4c4ba91a00
  Running setup.py bdist_wheel for bz2file ... done
  Stored in directory: /Users/heytitle/Library/Caches/pip/wheels/31/9c/20/996d65ca104cbca940b1b053299b68459391c01c774d073126
Successfully built smart-open bz2file


In [ ]:
import spacy
nlp = spacy.load('en')
doc = nlp(u'This is a sentence')

In [2]:
[(-1,1)]*2

[(-1, 1), (-1, 1)]

In [3]:
a = [(-1,1)]*2

In [5]:
a[0][0] = 2

TypeError: 'tuple' object does not support item assignment

In [7]:
import numpy as np

In [15]:
np.random.seed(7)
print(np.random.uniform(-1,1, (10,2)))
print(np.random.uniform(-1,1, (10,2)))

[[ -8.47383421e-01   5.59837584e-01]
 [ -1.23181537e-01   4.46930356e-01]
 [  9.55979024e-01   7.69917408e-02]
 [  2.24092732e-03  -8.55897733e-01]
 [ -4.63122040e-01  -2.34998349e-04]
 [  3.58459992e-01   6.07478072e-01]
 [ -2.38117734e-01  -8.68127306e-01]
 [ -4.23708801e-01   8.19187055e-01]
 [ -5.73229293e-01  -9.57520764e-02]
 [  8.62412039e-01  -9.50201545e-01]]
[[ 0.20109783  0.900259  ]
 [-0.53939424  0.09697984]
 [ 0.81825675 -0.73366111]
 [ 0.04682516  0.50081972]
 [ 0.33802648 -0.06449428]
 [-0.59030182 -0.01846822]
 [-0.25523062 -0.04519769]
 [-0.26821923  0.67583599]
 [ 0.53729501 -0.37201065]
 [ 0.14525067 -0.4479019 ]]


In [16]:
np.random.seed(7)
print(np.random.uniform(-1,1, (10,2)))
print(np.random.uniform(-1,1, (10,2)))

[[ -8.47383421e-01   5.59837584e-01]
 [ -1.23181537e-01   4.46930356e-01]
 [  9.55979024e-01   7.69917408e-02]
 [  2.24092732e-03  -8.55897733e-01]
 [ -4.63122040e-01  -2.34998349e-04]
 [  3.58459992e-01   6.07478072e-01]
 [ -2.38117734e-01  -8.68127306e-01]
 [ -4.23708801e-01   8.19187055e-01]
 [ -5.73229293e-01  -9.57520764e-02]
 [  8.62412039e-01  -9.50201545e-01]]
[[ 0.20109783  0.900259  ]
 [-0.53939424  0.09697984]
 [ 0.81825675 -0.73366111]
 [ 0.04682516  0.50081972]
 [ 0.33802648 -0.06449428]
 [-0.59030182 -0.01846822]
 [-0.25523062 -0.04519769]
 [-0.26821923  0.67583599]
 [ 0.53729501 -0.37201065]
 [ 0.14525067 -0.4479019 ]]


In [1]:
import imp
imp.find_module('scipy')

(None,
 '/Users/heytitle/projects/neural-network-project/python3-env/lib/python3.5/site-packages/scipy',
 ('', '', 5))

In [3]:
import numpy as np

In [5]:
np.random.choice(5, 5)

array([1, 4, 4, 3, 1])

In [6]:
import itertools

In [14]:
dim = 4
permutedIndx = list(itertools.permutations(range(dim), dim))

In [15]:
len(permutedIndx)

24

In [13]:
4*3*2

120

In [16]:
permutedIndx

[(0, 1, 2, 3),
 (0, 1, 3, 2),
 (0, 2, 1, 3),
 (0, 2, 3, 1),
 (0, 3, 1, 2),
 (0, 3, 2, 1),
 (1, 0, 2, 3),
 (1, 0, 3, 2),
 (1, 2, 0, 3),
 (1, 2, 3, 0),
 (1, 3, 0, 2),
 (1, 3, 2, 0),
 (2, 0, 1, 3),
 (2, 0, 3, 1),
 (2, 1, 0, 3),
 (2, 1, 3, 0),
 (2, 3, 0, 1),
 (2, 3, 1, 0),
 (3, 0, 1, 2),
 (3, 0, 2, 1),
 (3, 1, 0, 2),
 (3, 1, 2, 0),
 (3, 2, 0, 1),
 (3, 2, 1, 0)]